/**
 * Generates `src/utils/posts-data.generated.ts` from the MDX files in
 * `src/posts`. The generated module bundles each post's raw frontmatter+body
 * as a string so the loader never reads the filesystem at runtime, plus the
 * post body pre-compiled to HTML so the worker never compiles MDX at runtime.
 *
 * Why: on Cloudflare Workers the runtime working directory has no `src/posts`,
 * so any `fs.readdirSync`/`readFileSync` of the posts at request time throws
 * EPERM. Bundling the content into the worker removes that failure mode.
 * Workers also disallow dynamic code generation (`new Function`), which is how
 * next-mdx-remote evaluates MDX at request time - so the markdown→HTML compile
 * has to happen here, at build time, instead of in the page.
 *
 * The pipeline below must stay in sync with what the post page used to pass to
 * MDXRemote: remark-gfm, rehype-slug, rehype-autolink-headings (behavior:
 * 'append'). rehype-slug must also keep matching `extractPostHeadings` in
 * `src/utils/posts.ts` (both use github-slugger) so TOC anchor links resolve.
 *
 * Runs automatically via the `prebuild` / `predev` npm hooks. After adding or
 * editing an archived post, run `pnpm gen:posts` (or just `pnpm build`).
 */
import fs from 'fs';
import path from 'path';

import matter from 'gray-matter';
import yaml from 'js-yaml';
import rehypeAutolinkHeadings from 'rehype-autolink-headings';
import rehypeSlug from 'rehype-slug';
import rehypeStringify from 'rehype-stringify';
import remarkGfm from 'remark-gfm';
import remarkParse from 'remark-parse';
import remarkRehype from 'remark-rehype';
import { unified } from 'unified';

const POSTS_DIR = path.join(process.cwd(), 'src', 'posts');
const OUT_FILE = path.join(process.cwd(), 'src', 'utils', 'posts-data.generated.ts');

async function main(): Promise<void> {
  if (!fs.existsSync(POSTS_DIR)) {
    throw new Error(`Posts directory not found: ${POSTS_DIR}`);
  }

  const files = fs
    .readdirSync(POSTS_DIR)
    .filter((file) => /\.mdx?$/.test(file))
    .sort();

  const processor = unified()
    .use(remarkParse)
    .use(remarkGfm)
    .use(remarkRehype)
    .use(rehypeSlug)
    .use(rehypeAutolinkHeadings, { behavior: 'append' })
    .use(rehypeStringify);

  const rawEntries: Record<string, string> = {};
  const htmlEntries: Record<string, string> = {};
  for (const file of files) {
    const slug = file.replace(/\.mdx?$/, '');
    const raw = fs.readFileSync(path.join(POSTS_DIR, file), 'utf-8');
    rawEntries[slug] = raw;
    // gray-matter targets js-yaml 3; the repo pins js-yaml 4 (no safeLoad),
    // so supply the v4 engine explicitly (same workaround as src/utils/posts.ts).
    const { content } = matter(raw, {
      engines: {
        yaml: { parse: (str: string) => yaml.load(str) as Record<string, unknown> },
      },
    });
    htmlEntries[slug] = String(await processor.process(content));
  }

  const banner =
    '// AUTO-GENERATED by scripts/generate-posts-data.ts — do not edit by hand.\n' +
    '// Run `pnpm gen:posts` to regenerate after changing files in src/posts.\n';
  const body =
    `export const RAW_POSTS: Record<string, string> = ${JSON.stringify(rawEntries, null, 2)};\n` +
    '\n' +
    `export const POST_HTML: Record<string, string> = ${JSON.stringify(htmlEntries, null, 2)};\n`;

  fs.writeFileSync(OUT_FILE, banner + '\n' + body, 'utf-8');
  console.log(
    `gen:posts: wrote ${files.length} posts to ${path.relative(process.cwd(), OUT_FILE)}`
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
