/**
 * Generates `src/utils/posts-data.generated.ts` from the MDX files in
 * `src/posts`. The generated module bundles each post's raw frontmatter+body
 * as a string so the loader never reads the filesystem at runtime.
 *
 * Why: on Cloudflare Workers the runtime working directory has no `src/posts`,
 * so any `fs.readdirSync`/`readFileSync` of the posts at request time throws
 * EPERM. Bundling the content into the worker removes that failure mode.
 *
 * Runs automatically via the `prebuild` / `predev` npm hooks. After adding or
 * editing an archived post, run `pnpm gen:posts` (or just `pnpm build`).
 */
import fs from 'fs';
import path from 'path';

const POSTS_DIR = path.join(process.cwd(), 'src', 'posts');
const OUT_FILE = path.join(process.cwd(), 'src', 'utils', 'posts-data.generated.ts');

function main(): void {
  if (!fs.existsSync(POSTS_DIR)) {
    throw new Error(`Posts directory not found: ${POSTS_DIR}`);
  }

  const files = fs
    .readdirSync(POSTS_DIR)
    .filter((file) => /\.mdx?$/.test(file))
    .sort();

  const entries: Record<string, string> = {};
  for (const file of files) {
    const slug = file.replace(/\.mdx?$/, '');
    entries[slug] = fs.readFileSync(path.join(POSTS_DIR, file), 'utf-8');
  }

  const banner =
    '// AUTO-GENERATED by scripts/generate-posts-data.ts — do not edit by hand.\n' +
    '// Run `pnpm gen:posts` to regenerate after changing files in src/posts.\n';
  const body = `export const RAW_POSTS: Record<string, string> = ${JSON.stringify(
    entries,
    null,
    2
  )};\n`;

  fs.writeFileSync(OUT_FILE, banner + '\n' + body, 'utf-8');
  console.log(
    `gen:posts: wrote ${files.length} posts to ${path.relative(process.cwd(), OUT_FILE)}`
  );
}

main();
